// react-dapp/src/components/SourceCode.tsx
import React from 'react'
import './SourceCode.css'
import githubLogo from '../assets/GitHub-Mark-32px.png'

function SourceCode() {
    return (
      <div className="source-code">
        <p>Source code:</p>
        <a href="https://github.com/energywebfoundation/iam-client-examples/tree/master/react-dapp">
          <img alt="GitHub Logo. Link to source code" src={githubLogo}/>
        </a>
      </div>
    )
}

export default SourceCode

// client/angular-dapp/src/app/source-code/source-code.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-source-code',
  templateUrl: './source-code.component.html',
  styleUrls: ['./source-code.component.css']
})
export class SourceCodeComponent {

}

<div class="source-code">
  <p>Source code:</p>
  <a href="https://github.com/energywebfoundation/iam-client-examples/tree/master/client/angular-dapp">
    <img src="./assets/GitHub-Mark-32px.png"/>
  </a>
</div>
